<<<<<<< HEAD
title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
=======
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
>>>>>>> 9bbe8863f0d5f7397b650aac914d2eab5feb8c5e
